export const ACTION_LABEL: Record<string, string> = {
  create: "Create",
  edit: "Edit",
  archive: "Archive",
  restore: "Restore",
  assignment: "Assignment",
  unassignment: "Unassignment",
  location_change: "Location change",
  status_change: "Status change",
  inspection: "Inspection",
  checkout: "Checkout",
  return: "Return",
  consumable_adjustment: "Consumable adjustment",
  consumable_allocation: "Consumable allocation",
  reservation: "Reservation",
  reservation_cancel: "Reservation cancelled",
  user_invite: "User invited",
  user_change: "User change",
  organization_change: "Organization change",
  attachment: "Attachment",
  qr: "QR",
  login: "Sign in",
};
